#!/bin/sh

set -e


mandb --quiet

if [ -e "/usr/share/kde4/apps/quassel/scripts/inxi" ]; then
	rm -f /usr/share/kde4/apps/quassel/scripts/inxi && ln -s /usr/bin/inxi /usr/share/kde4/apps/quassel/scripts/inxi
fi


#DEBHELPER#

exit 0
